from django.contrib import admin
from zfitcoy.models import*

# Register your models here.
admin.site.register(Blog_category)
admin.site.register(Team)
admin.site.register(Blogs)
admin.site.register(Services)
admin.site.register(Contact)
admin.site.register(TERMS_CONDITIONSs)
admin.site.register(PRIVACY_POLICYs)
admin.site.register(faqss)
admin.site.register(COMPANEY_SUPPORTS)
admin.site.register(WHY_CHOOSE_Us)
admin.site.register(Space)
admin.site.register(Water)
admin.site.register(Fire)
admin.site.register(Air)
admin.site.register(Earth)
admin.site.register(MCQQUCTIONS)
admin.site.register(MCQANSWERS)
admin.site.register(QuesModel)
admin.site.register(MCQUSER)
admin.site.register(Appionment)
admin.site.register(Body_Typess)
admin.site.register(SERVICE_CONTACT)