# Generated by Django 3.2.4 on 2021-08-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
