# Generated by Django 4.0.2 on 2022-05-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
