# Generated by Django 3.2.4 on 2021-08-25 20:12

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0002_team_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='categorys',
        ),
        migrations.AddField(
            model_name='team',
            name='post',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', djrichtextfield.models.RichTextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
                ('categorys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zfitcoy.blog_category')),
            ],
        ),
    ]
