# Generated by Django 3.2.4 on 2021-08-25 20:47

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0003_auto_20210825_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('detail', djrichtextfield.models.RichTextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('Logo', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
