# Generated by Django 3.2.4 on 2021-08-25 21:06

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0004_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.AddField(
            model_name='services',
            name='discription',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
