# Generated by Django 4.0.2 on 2022-05-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0004_alter_blogs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
