# Generated by Django 3.2.4 on 2021-08-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
