# Generated by Django 3.2.4 on 2021-09-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0009_air_earth_fire_space_water'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COMPANEY_LISENCE',
            new_name='WHY_CHOOSE_Us',
        ),
    ]
