# Generated by Django 3.2.4 on 2021-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0010_rename_companey_lisence_why_choose_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quction', models.CharField(max_length=50, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
