# Generated by Django 3.2.4 on 2021-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0011_faqss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
        migrations.AlterField(
            model_name='faqss',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
