# Generated by Django 3.2.4 on 2021-09-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0013_mcqquctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquctions',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='mcqquctions',
            name='que',
        ),
        migrations.AddField(
            model_name='mcqquctions',
            name='choice1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcqquctions',
            name='choice2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcqquctions',
            name='choice3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcqquctions',
            name='choice4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcqquctions',
            name='quctions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
