# Generated by Django 3.2.4 on 2021-09-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0014_auto_20210905_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquctions',
            name='quctions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
