# Generated by Django 3.2.4 on 2021-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0015_alter_mcqquctions_quctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQANSWERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=200, null=True)),
                ('choice2', models.CharField(max_length=200, null=True)),
                ('choice3', models.CharField(blank=True, max_length=200, null=True)),
                ('choice4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
