# Generated by Django 3.2.4 on 2021-09-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0017_quesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqanswers',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='mcqanswers',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='mcqanswers',
            name='choice4',
        ),
        migrations.AddField(
            model_name='mcqanswers',
            name='quctions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
