# Generated by Django 3.2.4 on 2021-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0018_auto_20210907_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquctions',
            name='choice4',
        ),
        migrations.AlterField(
            model_name='mcqquctions',
            name='choice1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mcqquctions',
            name='choice2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mcqquctions',
            name='quctions',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
