# Generated by Django 3.2.4 on 2021-09-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0019_auto_20210907_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQUSER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mcqanswers',
            name='categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zfitcoy.mcquser'),
        ),
    ]
