# Generated by Django 3.2.4 on 2021-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0020_auto_20210907_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquctions',
            name='choice4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
