# Generated by Django 3.2.4 on 2021-09-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0021_mcqquctions_choice4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Logo',
        ),
    ]
