# Generated by Django 3.2.4 on 2021-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0022_remove_services_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='detail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
