# Generated by Django 3.2.4 on 2021-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0023_alter_services_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appionment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('mobile', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=500, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
