# Generated by Django 3.2.7 on 2021-09-22 14:40

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0024_appionment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_Typess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
    ]
