# Generated by Django 3.2.7 on 2021-09-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0025_body_typess'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICE_CONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('age', models.IntegerField(max_length=50, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
