# Generated by Django 3.2.7 on 2021-09-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0026_service_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_contact',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
